apiVersion: v1
kind: Service
metadata:
  name: nlb-service
  labels:
   app: nginx
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb 

spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
    - port: 8080
      targetPort: 80